version: 2.0.0-{build}

clone_depth: 20

image:
- Visual Studio 2015
- Visual Studio 2017

environment:
  matrix:
    - PYTHON: C:\\Python27-x64
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 64
      PYTHONOPTIMIZE: 2
      DISTUTILS_USE_SDK: 1
      MSSdk: 1
      WINDOWS_SDK_VERSION: v7.0
      SET_SDK_64: Y

    - PYTHON: C:\\Python27
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32
      PYTHONOPTIMIZE: 2
      WINDOWS_SDK_VERSION: v7.0
      SET_SDK_64: Y

# skip_non_tags: true

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'
  # Cache PyInstaller build bundle env
  - C:\projects\dicogis\build\

install:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -c \"import sys, platform, struct;
    print(sys.platform, platform.machine(), struct.calcsize('P')*8)\""
  # list Windows SDKs
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Upgrade pip & co
  - "python -m pip install -U pip"
  # dependencies
  - "python -m pip install -U setuptools wheel"
  - "python -m pip install -U pip"
  - "python -m pip install -U -r requirements.txt"
  - "python -m pip install -U -r requirements_dev.txt"
  # Make sure the help options print.
  - "%PYTHON%\\Scripts\\pyinstaller.exe -v"

build: off

build_script:
  # Building the executable
  - "%PYTHON%\\Scripts\\pyinstaller.exe -y bundle_dicogis.spec"

  # Zip
  #- 7z a "IsogeoToOffice_%APPVEYOR_REPO_BRANCH%_%APPVEYOR_BUILD_WORKER_IMAGE%_x%PYTHON_ARCH%.zip" %APPVEYOR_BUILD_FOLDER%\dist\*

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  #- path: 'IsogeoToOffice_$(APPVEYOR_REPO_BRANCH)_$(APPVEYOR_BUILD_WORKER_IMAGE)_x%PYTHON_ARCH%.zip'
  #  name: 'IsogeoToOffice_$(APPVEYOR_REPO_BRANCH)_$(APPVEYOR_BUILD_WORKER_IMAGE)_x%PYTHON_ARCH%.zip'
