# Packaging to a Windows executable

pool:
  vmImage: "windows-2019"
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip setuptools wheel
    python -m pip install numpy
    python -m pip install .\lib\GDAL-3.0.0-cp37-cp37m-win_amd64.whl
  displayName: 'Install dependencies'
