# Packaging to a Windows executable

pool:
  vmImage: "windows-2019"
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  fetchDepth: 10  # the depth of commits to ask Git to fetch
  lfs: 1 

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip setuptools wheel
    python -m pip install numpy
    python -m pip install .\lib\GDAL-3.0.0-cp37-cp37m-win_amd64.whl
  displayName: 'Install dependencies'
