from Infos_Rasters import Read_Rasters
from Infos_GDB import Read_GDB
from Infos_SHP import Read_SHP
from Infos_TAB import Read_TAB
from Infos_GML import Read_GML
from Infos_KML import Read_KML
from Infos_GJSON import Read_GeoJSON
from Infos_GXT import ReadGXT
from Infos_PostGIS import Read_PostGIS
from Infos_DXF import Read_DXF
from Infos_GeoPDF import Read_GeoPDF
from Infos_Spatialite import Read_SpaDB
from Infos_Isogeo_OC import Read_IsogeoOpenCatalog
from Infos_LYR import Read_LYR
