from __future__ import absolute_import
from .Infos_Rasters import ReadRasters
from .Infos_GDB import ReadGDB
from .Infos_SHP import ReadSHP
from .Infos_TAB import ReadTAB
from .Infos_GML import ReadGML
from .Infos_KML import ReadKML
from .Infos_GJSON import ReadGeoJSON
from .Infos_GXT import ReadGXT
from .Infos_PostGIS import ReadPostGIS
from .Infos_DXF import ReadDXF
from .Infos_GeoPDF import ReadGeoPDF
from .Infos_Spatialite import ReadSpaDB
from .Infos_Isogeo_OC import ReadIsogeoOpenCatalog
from .Infos_LYR import ReadLYR
from .Infos_MXD import ReadMXD
